#!/usr/bin/env python3
"""
Rebuilds catalog-index.md from catalog.md: one line per document,
carrying only the fields that answer "is this the entry I want to open?"

Why this file exists: catalog.md is read at the start of essentially
every literature session, and roughly 70% of that read is fields that
only matter once you are already looking at one specific document
(`approach`, `compares`, `note`/`source` paths, `authors`). The index
keeps the "read the cheap thing in full" habit affordable as the corpus
grows into the hundreds, and catalog.md becomes the per-entry lookup
target - grepped one <!-- entry:ID --> block at a time, not read whole.

Derived file. Never hand-edit it; validate_repo.py checks it is fresh.

Usage: python scripts/build_catalog_index.py
"""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CATALOG_PATH = REPO_ROOT / "catalog.md"
INDEX_PATH = REPO_ROOT / "catalog-index.md"

ENTRY_FIELDS = {
    "title", "authors", "year", "type", "approach", "contribution",
    "compares", "tags", "note", "source", "summary",
}
ENTRY_RE = re.compile(
    r"^<!--\s*entry:(?P<id>.+?)\s*-->(?P<body>.*?)^<!--\s*/entry\s*-->",
    re.DOTALL | re.MULTILINE,
)
FIELD_START_RE = re.compile(r"^(" + "|".join(ENTRY_FIELDS) + r"):\s?(.*)$")

HEADER = """# Catalog index

**Read this file in full — it is the cheap default and should answer
most questions on its own.** One line per document, covering only what
is needed to decide *which* entry to open: title, year, type,
contribution, tags, and the summary.

Everything else about a document (`authors`, `approach`, `compares`, and
the paths to its note and source) lives in `catalog.md`. Don't read that
file whole — grep it and read the single `<!-- entry:ID -->` block you
need. The full text is in `notes/`, expensive, opened only to verify a
specific claim.

Auto-generated by `scripts/build_catalog_index.py` from `catalog.md`.
**Never hand-edit this file** — `scripts/validate_repo.py` checks that
it is up to date, and any manual change is overwritten on the next
build. Rerun after every batch:

```
python scripts/build_catalog_index.py
```

{stats}

---

"""


def parse_catalog(text):
    entries = []
    for m in ENTRY_RE.finditer(text):
        entry_id = m.group("id").strip()
        fields = {k: "" for k in ENTRY_FIELDS}
        current = None
        for line in m.group("body").splitlines():
            fm = FIELD_START_RE.match(line)
            if fm:
                current = fm.group(1)
                fields[current] = fm.group(2).strip()
            elif current and line.strip():
                fields[current] = (fields[current] + " " + line.strip()).strip()
        entries.append((entry_id, fields))
    return entries


def is_processed(fields):
    return bool(fields["summary"]) and "TODO" not in fields["summary"]


def format_entry(entry_id, f):
    """One entry, one bullet. Kept to a predictable shape so the file
    stays greppable: bold title, parenthesised identity fields, tags,
    summary, then the anchor back into catalog.md."""
    ident = ", ".join(x for x in (f["year"], f["type"], f["contribution"]) if x)
    parts = [f"- **{f['title'] or entry_id}**"]
    if ident:
        parts.append(f"({ident})")
    line = " ".join(parts)
    if f["tags"]:
        line += f" — {f['tags']}"
    if f["summary"]:
        line += f" — {f['summary']}"
    line += f" [`{entry_id}`]"
    return line


def build(entries):
    processed, stubs = [], []
    for entry_id, f in entries:
        if entry_id == "EXAMPLE":
            continue
        (processed if is_processed(f) else stubs).append((entry_id, f))

    processed.sort(key=lambda e: (e[1]["title"] or e[0]).lower())
    stubs.sort(key=lambda e: (e[1]["title"] or e[0]).lower())

    stats = (
        f"{len(processed)} annotated "
        f"{'entry' if len(processed) == 1 else 'entries'}"
    )
    if stubs:
        stats += f", plus {len(stubs)} not yet annotated (listed at the bottom)"
    stats += ", sorted alphabetically by title."

    lines = [HEADER.format(stats=stats).rstrip("\n"), ""]
    if processed:
        for entry_id, f in processed:
            lines.append(format_entry(entry_id, f))
    else:
        lines.append(
            "<!-- No annotated entries yet. Convert some documents with "
            "scripts/convert.py, fill in their catalog fields, then rerun "
            "this script. -->"
        )
    if stubs:
        lines.append("")
        lines.append("## Not yet annotated")
        lines.append("")
        lines.append(
            "Converted but without a filled-in catalog entry — these are "
            "invisible to any question asked of this index until someone "
            "reads them. See `ai_instructions/workflow.md`."
        )
        lines.append("")
        for entry_id, f in stubs:
            lines.append(f"- **{f['title'] or entry_id}** [`{entry_id}`]")
    lines.append("")
    return "\n".join(lines)


def main():
    if not CATALOG_PATH.exists():
        print(f"No {CATALOG_PATH} found.", file=sys.stderr)
        return 1

    entries = parse_catalog(CATALOG_PATH.read_text(encoding="utf-8"))
    new_text = build(entries)
    old_text = INDEX_PATH.read_text(encoding="utf-8") if INDEX_PATH.exists() else ""

    if new_text == old_text:
        print(f"No change. catalog-index.md is up to date ({len(entries)} entries in catalog.md).")
        return 0

    INDEX_PATH.write_text(new_text, encoding="utf-8")
    print(f"Rebuilt catalog-index.md from {len(entries)} catalog entries.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
